#!/bin/bash
set -e

REPO_DIR=$(git rev-parse --show-toplevel)
TESTS_DIR="$REPO_DIR/lua/tests"
INIT_FILE="$TESTS_DIR/init.vim"
MINIMAL_INIT_FILE="$TESTS_DIR/minimal_init.lua"

if [ "$SEQUENTIAL" == 1 ]; then
	SEQUENTIAL="sequential = true,"
fi

if [ -n "$1" ]; then
	nvim -u "$MINIMAL_INIT_FILE" --headless -c "lua require('plenary.busted').run('$1')"
else
	nvim -u "$MINIMAL_INIT_FILE" --headless -c "lua require('plenary.test_harness').test_directory( '$TESTS_DIR', { $SEQUENTIAL minimal_init = '$MINIMAL_INIT_FILE' })" -c "qa!"
fi
